services:
  bazarek:
    build:
      context: ./web_market
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web_market/app/data:/app/app/data
    restart: unless-stopped
