"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Pencil, Trash2, Users, X } from "lucide-react";

type Record={id:number;customerId?:number;customerName:string;phone:string;address:string};
type Customer={id:number;name:string;mobile:string;phone:string;address:string;group:string;description:string;active:boolean};
type Data={records:Record[];serviceTypes:string[];operators:string[]}; const blank:Data={records:[],serviceTypes:[],operators:[]};
const digits=(v:string)=>v.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/\D/g,"");

export default function MobileServicesSettingsPage(){
 const[data,setData]=useState<Data>(blank),[customers,setCustomers]=useState<Customer[]>([]),[service,setService]=useState(""),[operator,setOperator]=useState(""),[editing,setEditing]=useState<Customer|null>(null),[query,setQuery]=useState("");
 useEffect(()=>{fetch("/api/database",{cache:"no-store"}).then(r=>r.json()).then(db=>{setData(db.mobileServices||blank);setCustomers(db.customers||[])})},[]);
 const saveServices=async(next:Data)=>{setData(next);await fetch("/api/database",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({section:"mobileServices",data:next})})};
 const saveCustomers=async(next:Customer[])=>{setCustomers(next);await fetch("/api/database",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({section:"customers",data:next})})};
 const add=(event:FormEvent,kind:"service"|"operator")=>{event.preventDefault();const value=(kind==="service"?service:operator).trim(),key=kind==="service"?"serviceTypes":"operators";if(value&&!data[key].includes(value))void saveServices({...data,[key]:[...data[key],value]});kind==="service"?setService(""):setOperator("")};
 const mobileCustomers=useMemo(()=>customers.filter(c=>c.group==="خدمات سیار"||data.records.some(r=>r.customerId===c.id)).filter(c=>`${c.name} ${c.mobile} ${c.phone}`.includes(query)).sort((a,b)=>a.name.localeCompare(b.name,"fa")),[customers,data.records,query]);
 const recordCount=(customer:Customer)=>data.records.filter(r=>r.customerId===customer.id||(!r.customerId&&r.customerName===customer.name&&digits(r.phone)===digits(customer.mobile||customer.phone))).length;
 const update=async(customer:Customer)=>{const nextCustomers=customers.map(c=>c.id===customer.id?customer:c);const nextRecords=data.records.map(r=>r.customerId===customer.id||(!r.customerId&&r.customerName===editing?.name&&digits(r.phone)===digits(editing.mobile||editing.phone))?{...r,customerId:customer.id,customerName:customer.name,phone:customer.mobile||customer.phone,address:customer.address}:r);await saveCustomers(nextCustomers);await saveServices({...data,records:nextRecords});setEditing(null)};
 const remove=async(customer:Customer)=>{const total=recordCount(customer);if(!window.confirm(`مشتری «${customer.name}» و ${total.toLocaleString("fa-IR")} سابقهٔ خدمات او حذف شود؟`))return;await saveCustomers(customers.filter(c=>c.id!==customer.id));await saveServices({...data,records:data.records.filter(r=>r.customerId!==customer.id)});};
 const List=({title,kind}:{title:string;kind:"serviceTypes"|"operators"})=><section className="rounded-2xl border border-oxblood/10 bg-white p-5 shadow-sm"><h2 className="font-black">{title}</h2><form onSubmit={e=>add(e,kind==="serviceTypes"?"service":"operator")} className="mt-4 flex gap-2"><input value={kind==="serviceTypes"?service:operator} onChange={e=>kind==="serviceTypes"?setService(e.target.value):setOperator(e.target.value)} placeholder={`افزودن ${title}`} className="min-w-0 flex-1 rounded-lg border border-oxblood/15 p-2"/><button className="rounded-lg bg-oxblood px-4 text-white">افزودن</button></form><div className="mt-4 flex flex-wrap gap-2">{data[kind].map(item=><span key={item} className="rounded-full bg-blush px-3 py-2 text-sm">{item}<button type="button" onClick={()=>void saveServices({...data,[kind]:data[kind].filter(x=>x!==item)})} className="mr-2 text-oxblood" aria-label={`حذف ${item}`}>×</button></span>)}</div></section>;
 return <main className="min-h-screen bg-blush p-5 text-oxblood-dark"><section className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black text-oxblood">تنظیمات خدمات سیار</h1><p className="mt-1 text-sm text-oxblood/60">خدمات، اپراتورها و مشتریان این بخش را مدیریت کنید.</p></div><Link href="/mobile-services" className="rounded-lg border border-oxblood/20 bg-white px-4 py-2">بازگشت</Link></header><div className="mt-6 grid gap-4 sm:grid-cols-2"><List title="نوع خدمات" kind="serviceTypes"/><List title="اپراتور دستگاه" kind="operators"/></div><section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Users className="text-oxblood"/><div><h2 className="font-black">مشتریان خدمات سیار</h2><p className="text-xs text-oxblood/55">ویرایش اطلاعات، روی همهٔ سوابق این مشتری اعمال می‌شود.</p></div></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجوی مشتری یا شماره" className="rounded-lg border border-oxblood/15 p-2 text-sm"/></div><div className="mt-4 divide-y divide-oxblood/10">{mobileCustomers.map(customer=><article key={customer.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><b>{customer.name}</b><p className="mt-1 text-sm text-oxblood/60">{customer.mobile||customer.phone||"بدون شماره"} · {recordCount(customer).toLocaleString("fa-IR")} سابقه</p><small className="text-oxblood/50">{customer.address||"بدون آدرس"}</small></div><div className="flex gap-2"><button type="button" onClick={()=>setEditing(customer)} className="inline-flex items-center gap-1 rounded-lg border border-oxblood/20 px-3 py-2 text-sm font-bold text-oxblood"><Pencil size={15}/>ویرایش</button><button type="button" onClick={()=>void remove(customer)} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700"><Trash2 size={15}/>حذف</button></div></article>)}{mobileCustomers.length===0&&<p className="py-8 text-center text-sm text-oxblood/55">مشتری خدمات سیاری پیدا نشد.</p>}</div></section>{editing&&<CustomerEditor customer={editing} onClose={()=>setEditing(null)} onSave={update}/>}</section></main>;
}
function CustomerEditor({customer,onClose,onSave}:{customer:Customer;onClose:()=>void;onSave:(customer:Customer)=>Promise<void>}){const[name,setName]=useState(customer.name),[phone,setPhone]=useState(customer.mobile||customer.phone),[address,setAddress]=useState(customer.address);return <div className="fixed inset-0 z-40 grid place-items-center bg-oxblood-dark/45 p-4"><form onSubmit={e=>{e.preventDefault();if(name.trim())void onSave({...customer,name:name.trim(),mobile:phone.trim(),phone:"",address:address.trim(),group:"خدمات سیار"})}} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><button type="button" onClick={onClose} className="float-left"><X/></button><h2 className="text-xl font-black">ویرایش مشتری خدمات سیار</h2><label className="mt-5 block text-sm font-bold">نام مشتری<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"/></label><label className="mt-3 block text-sm font-bold">شماره تماس<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" className="mt-1 w-full rounded-lg border p-2 font-normal"/></label><label className="mt-3 block text-sm font-bold">آدرس<input value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 w-full rounded-lg border p-2 font-normal"/></label><div className="mt-5 flex gap-2"><button className="flex-1 rounded-lg bg-oxblood py-2.5 font-bold text-white">ذخیره تغییرات</button><button type="button" onClick={onClose} className="rounded-lg border px-4">انصراف</button></div></form></div>}
